version: "3.9"

services:
  cognitute-application:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../..:/workspace:cached
    command: sleep infinity
    networks:
      - cognitute-network
  db:
    networks:
      - cognitute-network
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
  # Add "forwardPorts": ["5432"] to **devcontainer.json** to forward PostgreSQL locally.
  # (Adding the "ports" property to this file will not forward from a Codespace.)

  pgAdmin:
    networks:
      - cognitute-network
    image: dpage/pgadmin4
    ports:
      - '5050:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    restart: unless-stopped
    
  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

networks:
  cognitute-network:
    driver: bridge

volumes:
  postgres-data:
  redisdata:
